export enum CONFIG {
	NODE_ENV = 'NODE_ENV',

	APP_TITLE = 'APP_TITLE',
	APP_PORT = 'APP_PORT',
	CONTACT_EMAIL = 'CONTACT_EMAIL',

	API_KEY = 'API_KEY',

	POSTGRES_HOST = 'POSTGRES_HOST',
	POSTGRES_PORT = 'POSTGRES_PORT',
	POSTGRES_USER = 'POSTGRES_USER',
	POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
	POSTGRES_DB = 'POSTGRES_DB',

	POSTMARK_API_KEY = 'POSTMARK_API_KEY',

	JWT_SECRET = 'JWT_SECRET',
	JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
	JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN',

	API_URL = 'API_URL',
	MCP_ACCESS_TOKEN_TTL = 'MCP_ACCESS_TOKEN_TTL',
	MCP_REFRESH_TOKEN_TTL = 'MCP_REFRESH_TOKEN_TTL',

	ROOT_ADMIN_PASSWORD = 'ROOT_ADMIN_PASSWORD',

	EMAIL_FROM_NAME = 'EMAIL_FROM_NAME',
	INFO_EMAIL = 'INFO_EMAIL',
	SUPPORT_EMAIL = 'SUPPORT_EMAIL',

	REDIS_HOST = 'REDIS_HOST',
	REDIS_PORT = 'REDIS_PORT',

	OPENAI_CUSTOM_API_KEY = 'OPENAI_CUSTOM_API_KEY',
	OPENAI_INTERNAL_API_KEY = 'OPENAI_INTERNAL_API_KEY',
	OPENAI_CONTEXT_API_KEY = 'OPENAI_CONTEXT_API_KEY',
	ANTHROPIC_API_KEY = 'ANTHROPIC_API_KEY',
	GEMINI_API_KEY = 'GEMINI_API_KEY',
	GROQ_API_KEY = 'GROQ_API_KEY',
	OPENROUTER_API_KEY = 'OPENROUTER_API_KEY',

	APIFY_TOKEN = 'APIFY_TOKEN',

	GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
	GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
	GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL',

	STRIPE_SECRET_KEY = 'STRIPE_SECRET_KEY',
	STRIPE_WEBHOOK_SECRET = 'STRIPE_WEBHOOK_SECRET',
	STRIPE_SUCCESS_URL = 'STRIPE_SUCCESS_URL',
	STRIPE_CANCEL_URL = 'STRIPE_CANCEL_URL',
	STRIPE_PRODUCT_ID = 'STRIPE_PRODUCT_ID',

	MINIO_HOST = 'MINIO_HOST',
	MINIO_PORT = 'MINIO_PORT',
	MINIO_USER = 'MINIO_USER',
	MINIO_PASS = 'MINIO_PASS',
	MINIO_BUCKET = 'MINIO_BUCKET',

	EXTENSION_FRONTEND_URL = 'EXTENSION_FRONTEND_URL',

	CRYPTO_SECRET = 'CRYPTO_SECRET',

	ADMIN_JWT_SECRET = 'ADMIN_JWT_SECRET',
	ADMIN_JWT_EXPIRES_IN = 'ADMIN_JWT_EXPIRES_IN',

	MIDBRAIN_API_URL = 'MIDBRAIN_API_URL',
	MIDBRAIN_API_KEY = 'MIDBRAIN_API_KEY',
}
