export enum DetectLanguage {
	ENGLISH = 'English',
	UKRAINIAN = 'Ukrainian',
	RUSSIAN = 'Russian',
	SPANISH = 'Spanish',
	FRENCH = 'French',
	GERMAN = 'German',
	ITALIAN = 'Italian',
	PORTUGUESE = 'Portuguese',
	POLISH = 'Polish',
	CZECH = 'Czech',
	ROMANIAN = 'Romanian',
	BULGARIAN = 'Bulgarian',
	CROATIAN = 'Croatian',
	SLOVAK = 'Slovak',
	SLOVENIAN = 'Slovenian',
	GREEK = 'Greek',
	TURKISH = 'Turkish',
	ARABIC = 'Arabic',
	HEBREW = 'Hebrew',
	HINDI = 'Hindi',
	CHINESE = 'Chinese',
	JAPANESE = 'Japanese',
	KOREAN = 'Korean',
	THAI = 'Thai',
	VIETNAMESE = 'Vietnamese',
}
